# This is a basic workflow that is manually triggered

name: refresh_steps

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

env:
  USER: ${{secrets.USR}}
  PW: ${{secrets.PW}}
on:
  watch:
    types: started
  schedule:
    - cron: '6 2,6,10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
        
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: execute
        run: |
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PW }}' 
          python3 main.py ${user} ${passwd}
          
          # source cron_convert.sh
          # echo "configed CRON_HOURS ${{ vars.CRON_HOURS }}"
          # persist_execute_log ${{ github.event_name }} ${{ vars.CRON_HOURS }}
          # git config user.name github-actions
          # git config user.email github-actions@users.noreply.github.com
          # git add .
          # current=`TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S'`
          # git commit -m "[${current}] random cron trigger by ${{ github.event_name }}"
          # git push origin master

